/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-17 15:17:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ESJ_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/JungHun/Project/JSP-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FromJ/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/JungHun/Project/JSP-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FromJ/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1755438329869L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>게시판</title>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/esj.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- 배너 영역 -->\r\n");
      out.write("        <div class=\"banner-section\">\r\n");
      out.write("            <img src=\"banner.png\" alt=\"게시판 배너\" class=\"banner-image\" id=\"bannerImage\" \r\n");
      out.write("                 onerror=\"this.style.display='none'; this.parentElement.classList.add('no-image');\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 글쓰기 버튼 -->\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <button type=\"button\" class=\"btn\" id=\"btnWrite\">새 글 쓰기</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn\" id=\"btnRefresh\">목록 새로고침</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 검색 영역 -->\r\n");
      out.write("        <div class=\"search-area\">\r\n");
      out.write("            <input type=\"text\" id=\"searchInput\" placeholder=\"제목, 내용, 작성자로 검색...\" style=\"width: 300px; padding: 5px;\">\r\n");
      out.write("            <button type=\"button\" class=\"btn\" id=\"btnSearch\">검색</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 카테고리 네비게이션 -->\r\n");
      out.write("        <div class=\"category-nav\">\r\n");
      out.write("            <strong>카테고리:</strong>\r\n");
      out.write("            <a href=\"#\" class=\"category-link active\" data-category=\"all\">전체</a>\r\n");
      out.write("            <a href=\"#\" class=\"category-link\" data-category=\"politics\">정치</a>\r\n");
      out.write("            <a href=\"#\" class=\"category-link\" data-category=\"economy\">경제</a>\r\n");
      out.write("            <a href=\"#\" class=\"category-link\" data-category=\"society\">사회</a>\r\n");
      out.write("            <a href=\"#\" class=\"category-link\" data-category=\"culture\">문화</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 게시글 목록 -->\r\n");
      out.write("        <div id=\"boardList\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"num\">번호</th>\r\n");
      out.write("                        <th class=\"thumbnail\">사진</th>\r\n");
      out.write("                        <th class=\"category-col\">분류</th>\r\n");
      out.write("                        <th class=\"title\">제목</th>\r\n");
      out.write("                        <th class=\"author\">작성자</th>\r\n");
      out.write("                        <th class=\"date\">날짜</th>\r\n");
      out.write("                        <th class=\"views\">조회</th>\r\n");
      out.write("                        <th class=\"actions\">관리</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody id=\"boardTableBody\">\r\n");
      out.write("                    <!-- jQuery AJAX로 로드됩니다 -->\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 페이징 -->\r\n");
      out.write("        <div class=\"pagination\" id=\"pagination\">\r\n");
      out.write("            <!-- jQuery로 생성됩니다 -->\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 게시글 상세보기 -->\r\n");
      out.write("        <div class=\"view-container\" id=\"postView\">\r\n");
      out.write("            <div class=\"view-header\">\r\n");
      out.write("                <div class=\"view-title\" id=\"postTitle\"></div>\r\n");
      out.write("                <div class=\"view-info\" id=\"postInfo\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"view-content\" id=\"postContent\"></div>\r\n");
      out.write("            <div class=\"view-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn\" id=\"btnList\">목록으로</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn\" id=\"btnEdit\">수정</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn\" id=\"btnDelete\">삭제</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 글쓰기 폼 -->\r\n");
      out.write("        <div class=\"form-container\" id=\"writeForm\">\r\n");
      out.write("            <h2 id=\"formTitle\">글쓰기</h2>\r\n");
      out.write("            <form id=\"postForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <input type=\"hidden\" id=\"postId\" name=\"id\">\r\n");
      out.write("                <input type=\"hidden\" id=\"formAction\" name=\"action\" value=\"write\">\r\n");
      out.write("                \r\n");
      out.write("                <table class=\"form-table\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>카테고리</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <select name=\"category\" id=\"writeCategory\" required>\r\n");
      out.write("                                <option value=\"\">선택하세요</option>\r\n");
      out.write("                                <option value=\"politics\">정치</option>\r\n");
      out.write("                                <option value=\"economy\">경제</option>\r\n");
      out.write("                                <option value=\"society\">사회</option>\r\n");
      out.write("                                <option value=\"culture\">문화</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>제목</th>\r\n");
      out.write("                        <td><input type=\"text\" name=\"title\" id=\"writeTitle\" size=\"50\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>작성자</th>\r\n");
      out.write("                        <td><input type=\"text\" name=\"author\" id=\"writeAuthor\" size=\"20\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>비밀번호</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"password\" name=\"password\" id=\"writePassword\" size=\"20\" required>\r\n");
      out.write("                            <small>(수정/삭제용, 4자리 이상)</small>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>내용</th>\r\n");
      out.write("                        <td><textarea name=\"content\" id=\"writeContent\" required></textarea></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>사진첨부</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"file\" name=\"images\" id=\"fileInput\" accept=\"image/*\">\r\n");
      out.write("                            <small>이미지 파일 1개만 업로드 가능 (최대 10MB)</small>\r\n");
      out.write("                            <div id=\"imagePreview\" class=\"image-preview\"></div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\" id=\"submitBtn\">등록</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn\" id=\"cancelBtn\">취소</button>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 비밀번호 확인 모달 -->\r\n");
      out.write("    <div class=\"modal\" id=\"passwordModal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">비밀번호 확인</div>\r\n");
      out.write("            <form id=\"passwordForm\">\r\n");
      out.write("                <table style=\"width: 100%;\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th style=\"width: 100px;\">비밀번호</th>\r\n");
      out.write("                        <td><input type=\"password\" id=\"modalPassword\" style=\"width: 100%;\" required></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn\">확인</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn\" id=\"passwordCancel\">취소</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 이미지 확대 모달 -->\r\n");
      out.write("    <div class=\"modal\" id=\"imageModal\">\r\n");
      out.write("        <div class=\"modal-content\" style=\"width: 80%; max-width: 800px;\">\r\n");
      out.write("            <div class=\"modal-header\">이미지 보기</div>\r\n");
      out.write("            <div style=\"text-align: center;\">\r\n");
      out.write("                <img id=\"largeImage\" style=\"max-width: 100%; max-height: 500px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn\" id=\"imageClose\">닫기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/board.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div>\r\n");
      out.write("    <!-- 메뉴 열기 버튼 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/body/chat.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
