/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-08-18 11:57:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.football.model.News;

public final class footballMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/LX/JSP-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FromJ/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1755517731655L));
    _jspx_dependants.put("jar:file:/C:/Users/LX/JSP-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FromJ/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.football.model.News");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("   <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("   <title>축구 읽어주는 여자</title>\r\n");
      out.write("   <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/football.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- Header -->\r\n");
      out.write("   <header>\r\n");
      out.write("       <div class=\"container\">\r\n");
      out.write("           <div class=\"header-content\">\r\n");
      out.write("               <a href=\"footballMain\" class=\"logo\">축구읽어주는 여자</a>\r\n");
      out.write("               <nav class=\"nav\">\r\n");
      out.write("                   <a href=\"/footballMain\">축구 소식통</a>\r\n");
      out.write("                   <a href=\"/football_world\">해외축구</a>\r\n");
      out.write("                   <a href=\"/football_korean\">국내축구</a>\r\n");
      out.write("                   <a href=\"ESJ.jsp\">게시판 글쓰기</a>        \r\n");
      out.write("               </nav>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </header>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <!-- Hero Section -->\r\n");
      out.write("   <section class=\"hero\">\r\n");
      out.write("       <div class=\"container\">\r\n");
      out.write("       \r\n");
      out.write("           <h1></h1>\r\n");
      out.write("           <p></p>\r\n");
      out.write("       </div>\r\n");
      out.write("   </section>\r\n");
      out.write("\r\n");
      out.write("   <!-- Breaking News Bar -->\r\n");
      out.write("	<div class=\"breaking-bar\">\r\n");
      out.write("	  <div class=\"breaking-wrap\">\r\n");
      out.write("	    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("   <!--네비게이션 2-->\r\n");
      out.write("   <div class=\"secondary-nav-container\">\r\n");
      out.write("       <ul class=\"secondary-nav-menu\">\r\n");
      out.write("           <li class=\"secondary-nav-item home\">\r\n");
      out.write("               <span>홈</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item\">\r\n");
      out.write("               <span>인기</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item epl active\">\r\n");
      out.write("               <span>EPL</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item esp\">\r\n");
      out.write("               <span>ESP</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item ita\">\r\n");
      out.write("               <span>ITA</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item ger\">\r\n");
      out.write("               <span>GER</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item fra\">\r\n");
      out.write("               <span>FRA</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item community\">\r\n");
      out.write("               <span>기타</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item sns\">\r\n");
      out.write("               <span>SNS</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item talk\">\r\n");
      out.write("               <span>TALK</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item job\">\r\n");
      out.write("               <span>잡담</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item stats\">\r\n");
      out.write("               <span>영상</span>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"secondary-nav-item event\">\r\n");
      out.write("               <span>이벤트</span>\r\n");
      out.write("           </li>\r\n");
      out.write("       </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <!-- 단축키 패널 -->\r\n");
      out.write("   <div class=\"shortcut-panel\">\r\n");
      out.write("       <div class=\"shortcut-header\">\r\n");
      out.write("           <span class=\"shortcut-title\">단축키</span>\r\n");
      out.write("           <button class=\"shortcut-toggle\">설정하기 ▶</button>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"shortcut-content\">\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">alt+c</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">댓글쓰기</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">alt+w</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">글쓰기</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">alt+q</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">댓글 등록</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">e</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">상단으로</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">s</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">이전</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">d</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">하단으로</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">f</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">다음</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">q</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">메인</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">w</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">인기글</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">1</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">프리미어리그</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">2</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">축구소식통</span>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div class=\"shortcut-item\">\r\n");
      out.write("               <span class=\"shortcut-key\">3</span>\r\n");
      out.write("               <span class=\"shortcut-desc\">축구소식</span>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- 메인 콘텐츠 섹션 (리그 순위 + 뉴스) -->\r\n");
      out.write("   <section class=\"main-content-section\">\r\n");
      out.write("       <div class=\"container\">\r\n");
      out.write("           <div class=\"content-wrapper\">\r\n");
      out.write("               <!-- 왼쪽: 리그 순위 -->\r\n");
      out.write("               <div class=\"league-section\">\r\n");
      out.write("                   <div class=\"section-title\">\r\n");
      out.write("                       <h2>리그 순위</h2>\r\n");
      out.write("                       <p class=\"section-subtitle\">프리미어리그 & 라리가 최신 순위</p>\r\n");
      out.write("                        <button id=\"refreshRankBtn\">순위 새로고침🗘</button>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class=\"league-container\">\r\n");
      out.write("                       <!-- 프리미어리그 -->\r\n");
      out.write("                       <div class=\"league-table\">\r\n");
      out.write("                           <div class=\"league-header\">\r\n");
      out.write("                               프리미어리그\r\n");
      out.write("                               <div class=\"season-info\">2025-26</div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"standings-list\">\r\n");
      out.write("                               ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       \r\n");
      out.write("                       <!-- 라리가 -->\r\n");
      out.write("                       <div class=\"league-table\">\r\n");
      out.write("                           <div class=\"league-header\">\r\n");
      out.write("                               라리가\r\n");
      out.write("                               <div class=\"season-info\">2025-26</div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"standings-list\">\r\n");
      out.write("                               ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- 오른쪽: 뉴스 섹션 -->\r\n");
      out.write("               <div class=\"news-section\">\r\n");
      out.write("                   <div class=\"section-title\">\r\n");
      out.write("                       <h2>축구 소식통</h2>\r\n");
      out.write("                       <p class=\"section-subtitle\">축구 소식통 최근 인기글</p>\r\n");
      out.write("                       <button id=\"refreshBtn\">소식 새로고침🗘</button>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   \r\n");
      out.write("                   <div class=\"news-list\">\r\n");
      out.write("                       ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   </div>\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Footer -->\r\n");
      out.write("   <footer>\r\n");
      out.write("       <div class=\"container\">\r\n");
      out.write("           <div class=\"footer-content\">\r\n");
      out.write("               <div class=\"footer-links\">\r\n");
      out.write("                   <a href=\"index.jsp\">홈</a>\r\n");
      out.write("                   <a href=\"ESJ.jsp\">어성준은 힘들다</a>\r\n");
      out.write("                   <a href=\"seoul_food.jsp\">서울맛집지도</a>\r\n");
      out.write("                   <a>이용약관</a>\r\n");
      out.write("                   <a>개인정보처리방침</a>\r\n");
      out.write("                   <a>문의/신고</a>\r\n");
      out.write("                   <a>게시글중단요청</a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <p class=\"footer-text\">© 2025 축구읽어주는 여자. All rights reserved.</p>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("   \r\n");
      out.write("   <script>  \r\n");
      out.write("	<!--JQuery-->\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	    window.handleClick = function(itemId) {\r\n");
      out.write("	        alert('클릭되었습니다. Item ID: ' + itemId);\r\n");
      out.write("	    };\r\n");
      out.write("	    \r\n");
      out.write("	    $(window).scroll(function() {\r\n");
      out.write("	        if($(window).scrollTop() > 100) {\r\n");
      out.write("	            $('header').css('box-shadow', '0 2px 20px rgba(0,0,0,0.1)');\r\n");
      out.write("	        } else {\r\n");
      out.write("	            $('header').css('box-shadow', 'none');\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("	    $(\"#refreshBtn\").click(function() {\r\n");
      out.write("	        var button = $(this);\r\n");
      out.write("	        button.prop(\"disabled\", true).text(\"새로고침 중...\");\r\n");
      out.write("	        \r\n");
      out.write("	        // Ajax로 서버에 요청\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            type: \"GET\",\r\n");
      out.write("	            url: window.location.href, // 현재 페이지 주소\r\n");
      out.write("	            data: \"ajax=true\", // Ajax 요청임을 표시\r\n");
      out.write("	            success: function(data) {\r\n");
      out.write("	                console.log(\"Ajax 성공!\");\r\n");
      out.write("	                // 1초 후 페이지 새로고침\r\n");
      out.write("	                setTimeout(function() {\r\n");
      out.write("	                    window.location.reload();\r\n");
      out.write("	                }, 1000);\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function() {\r\n");
      out.write("	                console.log(\"Ajax 실패\");\r\n");
      out.write("	                alert(\"새로고침 실패\");\r\n");
      out.write("	                button.prop(\"disabled\", false).text(\"소식 새로고침\");\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(\"#refreshRankBtn\").click(function() {\r\n");
      out.write("	    var button = $(this);\r\n");
      out.write("	    button.prop(\"disabled\", true).text(\"새로고침 중...\");\r\n");
      out.write("	    \r\n");
      out.write("	    $.ajax({\r\n");
      out.write("	        type: \"GET\",\r\n");
      out.write("	        data: \"ajax=rank\",         \r\n");
      out.write("	        success: function(data) {\r\n");
      out.write("	            setTimeout(function() {\r\n");
      out.write("	                window.location.reload();\r\n");
      out.write("	            }, 1000);\r\n");
      out.write("	        },\r\n");
      out.write("	        error: function() {\r\n");
      out.write("	            alert(\"순위 새로고침 실패!\");\r\n");
      out.write("	            button.prop(\"disabled\", false).text(\"순위 새로고침\");\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		<!-- 메뉴 열기 버튼 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "body/chat.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /footballMain.jsp(46,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("brief");
    // /footballMain.jsp(46,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/footballMain.jsp(46,5) '${breakingNews}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${breakingNews}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	      <span class=\"breaking-item\">\r\n");
          out.write("	        <span class=\"breaking-dot\"></span> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brief.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("	      </span>\r\n");
          out.write("	    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /footballMain.jsp(177,31) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("team");
    // /footballMain.jsp(177,31) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/footballMain.jsp(177,31) '${premierLeague}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${premierLeague}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                   <div class=\"standing-item\">\r\n");
          out.write("                                       <span class=\"position\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${team.position}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("                                       <span class=\"team-name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${team.teamName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("                                   </div>\r\n");
          out.write("                               ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /footballMain.jsp(193,31) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("team");
    // /footballMain.jsp(193,31) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/footballMain.jsp(193,31) '${laLiga}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${laLiga}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                   <div class=\"standing-item\">\r\n");
          out.write("                                       <span class=\"position\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${team.position}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("                                       <span class=\"team-name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${team.teamName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("                                   </div>\r\n");
          out.write("                               ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /footballMain.jsp(213,23) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("news");
    // /footballMain.jsp(213,23) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/footballMain.jsp(213,23) '${newsList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${newsList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /footballMain.jsp(213,23) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVarStatus("status");
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                           <div class=\"news-item\">\r\n");
          out.write("                               <span class=\"news-number\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("                               <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.imageUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"news-thumbnail\">\r\n");
          out.write("                               <div class=\"news-content\">\r\n");
          out.write("                                   <div class=\"news-item-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("                                   <div class=\"news-meta\">\r\n");
          out.write("                                       ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" | \r\n");
          out.write("                                       ");
          if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
            return true;
          out.write(" | \r\n");
          out.write("                                       <span class=\"comment-count\">[");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.commentCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("]</span>\r\n");
          out.write("                                   </div>\r\n");
          out.write("                               </div>\r\n");
          out.write("                           </div>\r\n");
          out.write("                       ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f3);
    // /footballMain.jsp(221,39) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.createdAt}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /footballMain.jsp(221,39) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("MM월 dd일 HH:mm:ss");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }
}
